version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app

  tests:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    command: yarn test
